default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres                                                               
  password:                                                                        
  host: db   

development:
  <<: *default
  database: purchase_development

test:
  <<: *default
  database: purchase_test

production:
  <<: *default
  database: purchase_production
  username: purchase
  password: <%= ENV['PURCHASE_DATABASE_PASSWORD'] %>
